[versions]
# TON
ton = "0.3.1"
# KotlinX Serialization
kotlinxSerialization = "1.9.0"
# Koin
koin = "4.1.1"
# OkHttp
okhttp = "5.1.0"
# Compose
compose = "2025.09.00"
# CameraX
cameraX = "1.4.2"
# Coil
coil = "3.3.0"


[libraries]
zxing = { module = "com.google.zxing:core", version = "3.5.3" }
j2objc = { module = "com.google.j2objc:j2objc-annotations", version = "3.1" }
cbor = { module = "co.nstant.in:cbor", version = "0.9" }
ble = { module = "no.nordicsemi.android:ble-ktx", version = "2.10.2" }
bcprovjdk = { module = "org.bouncycastle:bcprov-jdk15to18", version = "1.81" }
web3j = { module = "org.web3j:core", version = "5.0.0" }
aptabase = { module = "com.github.aptabase:aptabase-kotlin", version = "0.0.8" }
okio = { module = "com.squareup.okio:okio", version = "3.16.0" }
material = { module = "com.google.android.material:material", version = "1.13.0" }
flexbox = { module = "com.google.android.flexbox:flexbox", version = "3.0.0" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version = "17.3.0" }
bleManager = { module = "com.github.cosmostation:hw-transport-android-ble", version = "0.0.8" }

# TON
ton-tvm = { module = "org.ton:ton-kotlin-tvm", version.ref = "ton" }
ton-crypto = { module = "org.ton:ton-kotlin-crypto", version.ref = "ton" }
ton-tlb = { module = "org.ton:ton-kotlin-tlb", version.ref = "ton" }
ton-blockTlb = { module = "org.ton:ton-kotlin-block-tlb", version.ref = "ton" }
ton-tonapiTl = { module = "org.ton:ton-kotlin-tonapi-tl", version.ref = "ton" }
ton-contract = { module = "org.ton:ton-kotlin-contract", version.ref = "ton" }

# KotlinX
kotlinX-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.2" }
kotlinX-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version = "1.10.2" }
kotlinX-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
kotlinX-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.0" }

# KotlinX Serialization
kotlinX-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinX-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinX-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }

# Google Play
google-play-base = { module = "com.google.android.gms:play-services-base", version = "18.8.0" }
google-play-cronet = { module = "com.google.android.gms:play-services-cronet", version = "18.1.0" }
google-play-review = { module = "com.google.android.play:review-ktx", version = "2.0.2" }
google-play-billing = { module = "com.android.billingclient:billing-ktx", version = "8.0.0" }
google-play-update = { module = "com.google.android.play:app-update-ktx", version = "2.1.0" }
google-play-installreferrer = { module = "com.android.installreferrer:installreferrer", version = "2.2" }

# Koin
koin-core = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundationLayout = { module = "androidx.compose.foundation:foundation-layout" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-debugTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.3" }

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Camera
cameraX-base = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
cameraX-core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
cameraX-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
cameraX-view = { module = "androidx.camera:camera-view", version.ref = "cameraX" }

# AndroidX
androidX-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidX-shortcuts = { module = "androidx.core:core-google-shortcuts", version = "1.1.0" }
androidX-appCompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidX-activity = { module = "androidx.activity:activity-ktx", version = "1.11.0" }
androidX-fragment = { module = "androidx.fragment:fragment-ktx", version = "1.8.9" }
androidX-recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
androidX-viewPager2 = { module = "androidx.viewpager2:viewpager2", version = "1.1.0" }
androidX-security = { module = "androidx.security:security-crypto", version = "1.1.0" }
androidX-workManager = { module = "androidx.work:work-runtime-ktx", version = "2.10.4" }
androidX-biometric = { module = "androidx.biometric:biometric", version = "1.1.0" }
androidX-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidX-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidX-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidX-browser = { module = "androidx.browser:browser", version = "1.9.0" }
androidX-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }
androidX-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version = "1.4.1" }
androidX-webkit = { module = "androidx.webkit:webkit", version = "1.14.0" }
androidX-concurrent = { module = "androidx.concurrent:concurrent-futures", version = "1.3.0" }
androidX-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.3" }
androidX-lifecycleSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version = "2.9.3" }
androidX-emoji = { module = "androidx.emoji2:emoji2", version = "1.6.0" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "34.2.0" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-config = { module = "com.google.firebase:firebase-config", version = "23.0.0" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-performance = { module = "com.google.firebase:firebase-perf" }

[plugins]
android-application = { id = "com.android.application", version = "8.12.3" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version = "2.2.10" }
android-library = { id = "com.android.library", version = "8.12.3" }
android-test = { id = "com.android.test", version = "8.12.3" }
android-baselineprofile = { id = "androidx.baselineprofile", version = "1.4.1" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.10" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.10" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "2.2.10" }
kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version = "8.12.3" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.2.10" }

firebase-services = { id = "com.google.gms.google-services", version = "4.4.3" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version = "2.0.1" }




